
server:
  port: 9010



spring:
  security:
    user:
      password: userpassword1
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_db
    username: root
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    openfeign:
      client:
        config:
          feignName:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  servlet:
    multipart:
      max-request-size: 2GB
      max-file-size: 2GB



