server:
  port: 9030

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5438/photo_db
    username: root
    password: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
        max-request-size: 2GB
        max-file-size: 2GB



application:
  config:
    client-url: http://localhost:9010/api
    product-url: http://localhost:9020/api

