spring:
  config:
    import: optional:configserver:http://localhost:9999
  application:
    name: clientService

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/eCommerce-realm"






