services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

networks:
  net-microservice:
    driver: bridge


volumes:
  postgres: