
services:
  clientDb:
    image: postgres:latest
    container_name: clientDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: client_db
    ports:
      - "5432:5432"
    volumes:
      - client_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

  productDb:
    image: postgres:latest
    container_name: productDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

  orderDb:
    image: postgres:latest
    container_name: orderDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: order_db
    ports:
      - "5434:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

  paymentDb:
    image: postgres:latest
    container_name: paymentDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: payment_db
    ports:
      - "5435:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

  photoDb:
    image: postgres:latest
    container_name: photoDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: photo_db
    ports:
      - "5438:5432"
    volumes:
      - photo_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped


  notificationDb:
    image: postgres:latest
    container_name: notificationDb
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: root
      POSTGRES_DB: notification_db
    ports:
      - "5437:5432"
    volumes:
      - notification_data:/var/lib/postgresql/data
    networks:
      - net-microservice
    restart: unless-stopped

networks:
  net-microservice:
    driver: bridge

volumes:
  client_data:
  product_data:
  order_data:
  payment_data:
  photo_data:
  notification_data:
