spring:
  config:
    import: optional:configserver:http://localhost:9999
  application:
    name: ApiGateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:7080/realms/eCommerce-realm"

app:
  config:
    keycloak:
      url: http://localhost:7080/
      realm: eCommerce-realm



  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          AuthService:
            provider: keycloak
            client-id: AuthService
            client-secret: p2cIcD139MHOaubt2XokjPMWS7KoOlKf
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
